In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/car_price_dataset.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         10000 non-null  object
 1   Model         10000 non-null  object
 2   Year          10000 non-null  int64
 3   Engine_Size   10000 non-null  float64
 4   Fuel_Type     10000 non-null  object
 5   Transmission  10000 non-null  object
 6   Mileage       10000 non-null  int64
 7   Doors         10000 non-null  int64
 8   Owner_Count   10000 non-null  int64
 9   Price         10000 non-null  int64
dtypes: float64(1), int64(5), object(4)
memory usage: 781.4+ KB

In [ ]:
df[df["Brand"]=="Toyota"]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
5,Toyota,Camry,2007,2.7,Petrol,Automatic,157889,4,4,7242
9,Toyota,RAV4,2005,3.1,Petrol,Manual,107724,2,5,6545
21,Toyota,RAV4,2000,4.6,Hybrid,Semi-Automatic,41814,2,2,8863
22,Toyota,RAV4,2003,2.0,Electric,Manual,136662,5,4,6266
34,Toyota,Corolla,2010,3.2,Diesel,Automatic,132454,4,4,9150
...,...,...,...,...,...,...,...,...,...,...
9946,Toyota,RAV4,2000,2.0,Petrol,Semi-Automatic,61667,3,5,4866
9959,Toyota,Corolla,2006,3.8,Petrol,Manual,138450,4,3,6931
9965,Toyota,Camry,2017,5.0,Electric,Manual,150119,4,1,13197
9975,Toyota,Corolla,2015,4.7,Petrol,Automatic,123316,3,2,12333
9989,Toyota,Corolla,2003,1.6,Diesel,Semi-Automatic,205647,4,4,2487

In [ ]:
df['Fuel_Type'].unique()

array(['Diesel', 'Hybrid', 'Electric', 'Petrol'], dtype=object)

In [ ]:
df[df["Fuel_Type"]=="Diesel"]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
0,Kia,Rio,2020,4.2,Diesel,Manual,289944,3,5,8501
2,Mercedes,GLA,2020,4.2,Diesel,Automatic,231440,4,2,11171
15,Volkswagen,Golf,2007,3.2,Diesel,Automatic,60103,2,1,9697
18,Kia,Rio,2000,3.4,Diesel,Semi-Automatic,257427,3,3,2351
25,Kia,Sportage,2011,1.8,Diesel,Automatic,92188,2,4,8856
...,...,...,...,...,...,...,...,...,...,...
9988,BMW,3 Series,2010,3.0,Diesel,Manual,105615,4,2,7987
9989,Toyota,Corolla,2003,1.6,Diesel,Semi-Automatic,205647,4,4,2487
9991,Mercedes,E-Class,2017,1.1,Diesel,Automatic,179286,5,1,8214
9995,Kia,Optima,2004,3.7,Diesel,Semi-Automatic,5794,2,4,8884
9999,Volkswagen,Tiguan,2001,2.1,Diesel,Manual,157882,3,3,3342

In [ ]:
df['Transmission'].unique()

array(['Manual', 'Automatic', 'Semi-Automatic'], dtype=object)

In [ ]:
df[df["Transmission"]=="Automatic"]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
1,Chevrolet,Malibu,2012,2.0,Hybrid,Automatic,5356,2,3,12092
2,Mercedes,GLA,2020,4.2,Diesel,Automatic,231440,4,2,11171
5,Toyota,Camry,2007,2.7,Petrol,Automatic,157889,4,4,7242
6,Honda,Civic,2010,3.4,Electric,Automatic,139584,3,1,11208
10,BMW,5 Series,2013,1.3,Hybrid,Automatic,296824,2,3,5863
...,...,...,...,...,...,...,...,...,...,...
9991,Mercedes,E-Class,2017,1.1,Diesel,Automatic,179286,5,1,8214
9992,BMW,5 Series,2016,1.2,Hybrid,Automatic,13386,3,5,12332
9996,Chevrolet,Impala,2002,1.4,Electric,Automatic,168000,2,1,6240
9997,BMW,3 Series,2010,3.0,Petrol,Automatic,86664,5,1,9866
9998,Ford,Explorer,2002,1.4,Hybrid,Automatic,225772,4,1,4084

In [ ]:
df['Year'] = df['Year'].astype(str)

In [ ]:
df[df['Year']=='2015']

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
53,Honda,Civic,2015,2.6,Electric,Semi-Automatic,66777,5,1,11864
62,Ford,Focus,2015,4.8,Electric,Automatic,100603,4,2,14887
84,Hyundai,Tucson,2015,1.6,Electric,Manual,259533,2,4,7009
85,Mercedes,C-Class,2015,4.1,Petrol,Automatic,197249,3,1,10255
130,Volkswagen,Passat,2015,4.7,Diesel,Manual,220366,5,1,8892
...,...,...,...,...,...,...,...,...,...,...
9881,Chevrolet,Malibu,2015,2.5,Diesel,Automatic,228993,2,3,8020
9883,BMW,5 Series,2015,4.9,Diesel,Manual,28128,2,4,12937
9937,Mercedes,GLA,2015,2.6,Diesel,Automatic,187667,2,1,8946
9952,Mercedes,GLA,2015,4.9,Electric,Automatic,14529,2,5,16709
9975,Toyota,Corolla,2015,4.7,Petrol,Automatic,123316,3,2,12333

In [ ]:
df[df['Price']<10000]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
0,Kia,Rio,2020,4.2,Diesel,Manual,289944,3,5,8501
4,Volkswagen,Golf,2003,2.6,Hybrid,Semi-Automatic,286618,3,3,2867
5,Toyota,Camry,2007,2.7,Petrol,Automatic,157889,4,4,7242
7,Kia,Sportage,2001,4.7,Electric,Semi-Automatic,157495,2,2,7950
8,Kia,Sportage,2014,2.6,Hybrid,Manual,98700,3,4,9926
...,...,...,...,...,...,...,...,...,...,...
9995,Kia,Optima,2004,3.7,Diesel,Semi-Automatic,5794,2,4,8884
9996,Chevrolet,Impala,2002,1.4,Electric,Automatic,168000,2,1,6240
9997,BMW,3 Series,2010,3.0,Petrol,Automatic,86664,5,1,9866
9998,Ford,Explorer,2002,1.4,Hybrid,Automatic,225772,4,1,4084
9999,Volkswagen,Tiguan,2001,2.1,Diesel,Manual,157882,3,3,3342

In [ ]:
df[df['Mileage']<50000]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
1,Chevrolet,Malibu,2012,2.0,Hybrid,Automatic,5356,2,3,12092
11,Volkswagen,Golf,2009,4.5,Hybrid,Manual,42795,4,3,11444
16,Hyundai,Elantra,2017,2.9,Electric,Automatic,38133,5,2,14837
17,Volkswagen,Tiguan,2006,4.5,Electric,Manual,41161,2,2,11576
19,Mercedes,GLA,2021,1.5,Petrol,Manual,34640,2,1,11207
...,...,...,...,...,...,...,...,...,...,...
9974,Mercedes,C-Class,2020,1.1,Diesel,Manual,16669,5,1,10866
9980,Honda,CR-V,2012,1.5,Petrol,Manual,37233,3,2,8455
9987,BMW,5 Series,2004,1.3,Diesel,Manual,19392,2,2,6212
9992,BMW,5 Series,2016,1.2,Hybrid,Automatic,13386,3,5,12332
9995,Kia,Optima,2004,3.7,Diesel,Semi-Automatic,5794,2,4,8884

In [ ]:
df[df['Model']=='Suv']

Empty DataFrame
Columns: [Brand, Model, Year, Engine_Size, Fuel_Type, Transmission, Mileage, Doors, Owner_Count, Price]
Index: []

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/disney_princess_popularity_dataset_300_rows.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PrincessName                300 non-null    object
 1   FirstMovieTitle             300 non-null    object
 2   FirstMovieYear              300 non-null    int64
 3   MovieRuntimeMinutes         300 non-null    int64
 4   NumberOfSongs               300 non-null    int64
 5   HasSoloSong                 300 non-null    object
 6   HasDuet                     300 non-null    object
 7   HairColor                   300 non-null    object
 8   EyeColor                    300 non-null    object
 9   OutfitPrimaryColor          300 non-null    object
 10  OutfitStyleEra              300 non-null    object
 11  IsRoyalByBirth              300 non-null    object
 12  HasAnimalSidekick           300 non-null    object
 13  SidekickType                230 non-null    object
 14  HasMagicalPowers            300 non-null    object
 15  MagicType                   247 non-null    object
 16  MainSetting                 300 non-null    object
 17  IsBasedOnRealStory          300 non-null    object
 18  CulturalOrigin              300 non-null    object
 19  SpeaksToAnimals             300 non-null    object
 20  FightsVillainDirectly       300 non-null    object
 21  RomanticSubplot             300 non-null    object
 22  MarriedByEnd                300 non-null    object
 23  VillainName                 300 non-null    object
 24  VillainType                 253 non-null    object
 25  IMDB_Rating                 300 non-null    float64
 26  RottenTomatoesScore         300 non-null    int64
 27  BoxOfficeMillions           300 non-null    int64
 28  AvgScreenTimeMinutes        300 non-null    int64
 29  NumMerchItemsOnAmazon       300 non-null    int64
 30  GoogleSearchIndex2024       300 non-null    int64
 31  InstagramFanPages           300 non-null    int64
 32  TikTokHashtagViewsMillions  300 non-null    int64
 33  Top3Hashtags                300 non-null    object
 34  IsIconic                    300 non-null    object
 35  PopularityScore             300 non-null    int64
dtypes: float64(1), int64(11), object(24)
memory usage: 84.5+ KB

In [ ]:
df['HairColor'].unique()

array(['Brown', 'Blonde', 'White', 'Black', 'Red'], dtype=object)

In [ ]:
df[df['HairColor']== 'Black']

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
7,Rapunzel,Rapunzel's Adventure,1987,79,3,No,No,Black,Hazel,Pink,...,88,1130,58,705,73,194,988,#TeamRapunzel #LoveRapunzel #RapunzelForever,No,61
9,Anna,Anna's Adventure,2010,108,1,Yes,Yes,Black,Brown,Pink,...,67,931,48,3995,48,113,472,#TeamAnna #LoveAnna #AnnaForever,No,96
24,Tiana,Tiana's Adventure,2019,108,4,Yes,Yes,Black,Brown,Pink,...,87,542,44,4788,59,84,554,#TeamTiana #LoveTiana #TianaForever,Yes,62
29,Mulan,Mulan's Adventure,1983,70,5,No,No,Black,Hazel,Green,...,95,350,31,3599,92,151,734,#TeamMulan #LoveMulan #MulanForever,No,91
35,Raya,Raya's Adventure,2007,87,1,No,No,Black,Brown,Pink,...,78,459,43,2239,94,32,219,#TeamRaya #LoveRaya #RayaForever,Yes,88
40,Merida,Merida's Adventure,1993,74,2,Yes,Yes,Black,Hazel,Blue,...,97,1072,33,3439,30,38,562,#TeamMerida #LoveMerida #MeridaForever,No,98
41,Rapunzel,Rapunzel's Adventure,1977,70,4,Yes,Yes,Black,Blue,Green,...,87,998,31,1780,87,54,235,#TeamRapunzel #LoveRapunzel #RapunzelForever,Yes,71
53,Tiana,Tiana's Adventure,1991,71,6,Yes,No,Black,Green,Blue,...,71,823,21,3735,71,191,151,#TeamTiana #LoveTiana #TianaForever,Yes,74
58,Belle,Belle's Adventure,1937,105,4,No,Yes,Black,Grey,Yellow,...,80,897,51,169,38,149,20,#TeamBelle #LoveBelle #BelleForever,Yes,81
59,Anna,Anna's Adventure,1991,105,2,Yes,Yes,Black,Green,Green,...,93,985,59,963,55,281,113,#TeamAnna #LoveAnna #AnnaForever,Yes,62
85,Aurora,Aurora's Adventure,1952,75,2,Yes,No,Black,Hazel,Green,...,94,605,22,3309,44,130,523,#TeamAurora #LoveAurora #AuroraForever,Yes,71
89,Pocahontas,Pocahontas's Adventure,2013,70,4,No,No,Black,Green,Pink,...,73,325,40,3650,99,62,185,#TeamPocahontas #LovePocahontas #PocahontasFor...,No,89
101,Mulan,Mulan's Adventure,1995,101,6,No,No,Black,Brown,Blue,...,77,1216,51,4849,90,239,343,#TeamMulan #LoveMulan #MulanForever,Yes,77
106,Merida,Merida's Adventure,1997,101,6,No,No,Black,Hazel,Pink,...,95,1263,39,237,69,61,543,#TeamMerida #LoveMerida #MeridaForever,Yes,82
112,Jasmine,Jasmine's Adventure,1938,107,3,Yes,No,Black,Brown,Green,...,81,1285,20,4074,65,240,356,#TeamJasmine #LoveJasmine #JasmineForever,Yes,55
117,Pocahontas,Pocahontas's Adventure,1942,83,3,No,No,Black,Brown,Blue,...,92,791,26,466,82,76,915,#TeamPocahontas #LovePocahontas #PocahontasFor...,Yes,70
118,Aurora,Aurora's Adventure,2010,84,4,Yes,No,Black,Blue,Pink,...,83,491,52,667,30,166,868,#TeamAurora #LoveAurora #AuroraForever,No,98
124,Belle,Belle's Adventure,1993,103,1,Yes,Yes,Black,Hazel,Yellow,...,77,968,34,3514,52,49,452,#TeamBelle #LoveBelle #BelleForever,Yes,52
125,Moana,Moana's Adventure,1999,75,2,Yes,Yes,Black,Green,Blue,...,80,247,30,3959,66,160,704,#TeamMoana #LoveMoana #MoanaForever,No,97
126,Rapunzel,Rapunzel's Adventure,2017,77,2,Yes,No,Black,Green,Yellow,...,93,626,58,853,50,144,428,#TeamRapunzel #LoveRapunzel #RapunzelForever,Yes,98
136,Mulan,Mulan's Adventure,2003,85,7,Yes,Yes,Black,Green,Pink,...,89,166,40,356,79,294,806,#TeamMulan #LoveMulan #MulanForever,Yes,71
146,Snow White,Snow White's Adventure,2014,86,5,Yes,Yes,Black,Blue,Pink,...,61,248,37,3774,59,56,656,#TeamSnow White #LoveSnow White #Snow WhiteFor...,No,85
148,Aurora,Aurora's Adventure,2016,76,2,No,No,Black,Hazel,Yellow,...,87,987,52,4686,83,277,428,#TeamAurora #LoveAurora #AuroraForever,No,75
150,Ariel,Ariel's Adventure,1999,107,7,Yes,No,Black,Blue,Purple,...,89,815,39,3363,54,254,303,#TeamAriel #LoveAriel #ArielForever,Yes,81
160,Moana,Moana's Adventure,1947,106,7,No,Yes,Black,Brown,Pink,...,76,396,41,3685,39,133,878,#TeamMoana #LoveMoana #MoanaForever,Yes,87
163,Ariel,Ariel's Adventure,1989,83,1,No,No,Black,Blue,Blue,...,91,523,37,1473,60,269,883,#TeamAriel #LoveAriel #ArielForever,No,88
165,Tiana,Tiana's Adventure,1967,98,6,Yes,Yes,Black,Brown,Pink,...,93,1019,52,1657,54,281,587,#TeamTiana #LoveTiana #TianaForever,No,72
169,Mulan,Mulan's Adventure,1972,107,1,No,No,Black,Green,Green,...,85,489,46,3145,34,172,340,#TeamMulan #LoveMulan #MulanForever,Yes,70
172,Mulan,Mulan's Adventure,1993,93,2,Yes,No,Black,Grey,Yellow,...,78,1217,37,3422,21,191,910,#TeamMulan #LoveMulan #MulanForever,No,52
174,Elsa,Elsa's Adventure,2010,82,6,No,No,Black,Grey,Pink,...,61,1180,43,1197,71,54,314,#TeamElsa #LoveElsa #ElsaForever,Yes,70
176,Tiana,Tiana's Adventure,1965,100,3,No,No,Black,Grey,Purple,...,87,1237,41,3192,34,179,833,#TeamTiana #LoveTiana #TianaForever,Yes,81
180,Jasmine,Jasmine's Adventure,2000,70,4,No,Yes,Black,Green,Pink,...,64,711,45,4518,93,56,632,#TeamJasmine #LoveJasmine #JasmineForever,Yes,73
181,Elsa,Elsa's Adventure,1965,78,6,Yes,Yes,Black,Green,Yellow,...,88,1113,39,599,78,35,917,#TeamElsa #LoveElsa #ElsaForever,No,93
182,Belle,Belle's Adventure,2003,93,6,No,Yes,Black,Green,Pink,...,93,1139,48,4979,54,49,834,#TeamBelle #LoveBelle #BelleForever,Yes,90
183,Elsa,Elsa's Adventure,1999,103,2,Yes,Yes,Black,Green,Blue,...,71,392,42,1663,54,56,133,#TeamElsa #LoveElsa #ElsaForever,Yes,85
184,Mulan,Mulan's Adventure,1987,94,5,No,Yes,Black,Green,Pink,...,90,1252,24,4998,57,236,585,#TeamMulan #LoveMulan #MulanForever,Yes,55
193,Raya,Raya's Adventure,1956,71,5,No,No,Black,Green,Purple,...,69,1163,25,4654,92,85,178,#TeamRaya #LoveRaya #RayaForever,No,83
205,Anna,Anna's Adventure,1962,109,1,Yes,Yes,Black,Brown,Green,...,95,867,33,1839,66,239,592,#TeamAnna #LoveAnna #AnnaForever,Yes,63
209,Tiana,Tiana's Adventure,1969,76,2,Yes,Yes,Black,Blue,Pink,...,63,1217,37,4709,78,67,752,#TeamTiana #LoveTiana #TianaForever,Yes,76
210,Ariel,Ariel's Adventure,2012,76,7,No,Yes,Black,Hazel,Blue,...,91,924,48,2256,22,83,576,#TeamAriel #LoveAriel #ArielForever,Yes,62
216,Rapunzel,Rapunzel's Adventure,2019,102,7,No,No,Black,Hazel,Pink,...,60,713,55,1610,75,206,23,#TeamRapunzel #LoveRapunzel #RapunzelForever,Yes,65
220,Merida,Merida's Adventure,1950,85,5,Yes,Yes,Black,Hazel,Yellow,...,84,942,47,293,87,78,601,#TeamMerida #LoveMerida #MeridaForever,Yes,65
222,Elsa,Elsa's Adventure,1954,96,6,No,Yes,Black,Grey,Pink,...,89,518,20,3444,55,80,987,#TeamElsa #LoveElsa #ElsaForever,No,85
228,Tiana,Tiana's Adventure,1947,71,7,Yes,No,Black,Brown,Yellow,...,92,1255,22,1204,87,106,178,#TeamTiana #LoveTiana #TianaForever,Yes,87
235,Belle,Belle's Adventure,1975,90,4,No,Yes,Black,Grey,Pink,...,74,395,60,4024,44,52,693,#TeamBelle #LoveBelle #BelleForever,Yes,54
238,Cinderella,Cinderella's Adventure,1950,77,2,No,Yes,Black,Blue,Purple,...,90,748,27,153,66,131,994,#TeamCinderella #LoveCinderella #CinderellaFor...,Yes,71
240,Anna,Anna's Adventure,1990,95,7,Yes,No,Black,Grey,Blue,...,86,224,54,721,40,73,907,#TeamAnna #LoveAnna #AnnaForever,Yes,70
253,Anna,Anna's Adventure,2021,87,3,Yes,Yes,Black,Grey,Purple,...,76,1017,39,3662,44,107,769,#TeamAnna #LoveAnna #AnnaForever,Yes,52
255,Pocahontas,Pocahontas's Adventure,1963,110,4,Yes,No,Black,Brown,Yellow,...,75,897,36,469,53,296,951,#TeamPocahontas #LovePocahontas #PocahontasFor...,No,73
264,Cinderella,Cinderella's Adventure,1989,103,3,No,Yes,Black,Brown,Yellow,...,94,696,29,1879,51,65,856,#TeamCinderella #LoveCinderella #CinderellaFor...,No,87
269,Moana,Moana's Adventure,1952,81,4,Yes,Yes,Black,Blue,Yellow,...,98,419,28,4143,41,210,328,#TeamMoana #LoveMoana #MoanaForever,Yes,52
271,Pocahontas,Pocahontas's Adventure,2009,98,5,Yes,Yes,Black,Brown,Purple,...,94,664,46,3643,23,150,155,#TeamPocahontas #LovePocahontas #PocahontasFor...,Yes,99
276,Mulan,Mulan's Adventure,1994,98,2,No,Yes,Black,Green,Purple,...,78,346,22,1347,20,138,10,#TeamMulan #LoveMulan #MulanForever,Yes,100
285,Moana,Moana's Adventure,1975,81,1,Yes,Yes,Black,Brown,Yellow,...,68,337,45,4298,79,53,974,#TeamMoana #LoveMoana #MoanaForever,No,63
291,Cinderella,Cinderella's Adventure,1964,82,2,Yes,Yes,Black,Brown,Purple,...,89,397,44,493,61,156,237,#TeamCinderella #LoveCinderella #CinderellaFor...,Yes,89
293,Moana,Moana's Adventure,1961,96,4,Yes,No,Black,Grey,Pink,...,78,729,50,4350,74,241,977,#TeamMoana #LoveMoana #MoanaForever,Yes,93

In [ ]:
df['EyeColor'].unique()

array(['Green', 'Brown', 'Hazel', 'Grey', 'Blue'], dtype=object)

In [ ]:
df[df['EyeColor']== 'Blue']

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
5,Jasmine,Jasmine's Adventure,2010,78,7,Yes,Yes,Brown,Blue,Blue,...,93,1245,59,555,67,216,454,#TeamJasmine #LoveJasmine #JasmineForever,Yes,61
6,Snow White,Snow White's Adventure,1986,97,2,No,Yes,Blonde,Blue,Pink,...,90,639,60,2265,79,118,971,#TeamSnow White #LoveSnow White #Snow WhiteFor...,No,94
20,Aurora,Aurora's Adventure,1977,72,7,No,Yes,Blonde,Blue,Yellow,...,82,1068,22,3215,48,85,513,#TeamAurora #LoveAurora #AuroraForever,No,54
30,Jasmine,Jasmine's Adventure,1996,82,4,Yes,No,Blonde,Blue,Purple,...,85,1077,55,4278,93,227,395,#TeamJasmine #LoveJasmine #JasmineForever,Yes,70
33,Raya,Raya's Adventure,1997,104,5,Yes,No,Blonde,Blue,Blue,...,83,300,32,110,80,23,810,#TeamRaya #LoveRaya #RayaForever,No,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,Aurora,Aurora's Adventure,1972,95,3,Yes,Yes,Blonde,Blue,Green,...,79,107,50,180,25,159,442,#TeamAurora #LoveAurora #AuroraForever,No,70
286,Snow White,Snow White's Adventure,2005,96,2,Yes,No,Red,Blue,Yellow,...,92,296,40,4038,59,117,319,#TeamSnow White #LoveSnow White #Snow WhiteFor...,Yes,59
292,Anna,Anna's Adventure,1956,95,3,No,No,Blonde,Blue,Green,...,93,578,59,523,46,91,140,#TeamAnna #LoveAnna #AnnaForever,Yes,72
297,Anna,Anna's Adventure,2020,70,2,No,Yes,White,Blue,Blue,...,72,935,25,1815,53,53,164,#TeamAnna #LoveAnna #AnnaForever,Yes,67
298,Tiana,Tiana's Adventure,1937,71,7,No,No,Red,Blue,Purple,...,86,463,54,2365,35,116,584,#TeamTiana #LoveTiana #TianaForever,No,76

In [ ]:
df[df['FirstMovieYear']>1990]

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
1,Mulan,Mulan's Adventure,1995,85,1,Yes,Yes,Blonde,Brown,Purple,...,91,688,52,4202,49,133,619,#TeamMulan #LoveMulan #MulanForever,Yes,78
5,Jasmine,Jasmine's Adventure,2010,78,7,Yes,Yes,Brown,Blue,Blue,...,93,1245,59,555,67,216,454,#TeamJasmine #LoveJasmine #JasmineForever,Yes,61
8,Anna,Anna's Adventure,2007,94,6,Yes,No,White,Brown,Pink,...,99,1250,33,2132,34,171,506,#TeamAnna #LoveAnna #AnnaForever,Yes,82
9,Anna,Anna's Adventure,2010,108,1,Yes,Yes,Black,Brown,Pink,...,67,931,48,3995,48,113,472,#TeamAnna #LoveAnna #AnnaForever,No,96
18,Mulan,Mulan's Adventure,1991,74,2,No,Yes,Blonde,Brown,Yellow,...,66,334,25,184,28,165,238,#TeamMulan #LoveMulan #MulanForever,Yes,51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,Snow White,Snow White's Adventure,2005,96,2,Yes,No,Red,Blue,Yellow,...,92,296,40,4038,59,117,319,#TeamSnow White #LoveSnow White #Snow WhiteFor...,Yes,59
294,Pocahontas,Pocahontas's Adventure,2019,95,7,No,Yes,Brown,Hazel,Blue,...,68,168,23,908,94,173,847,#TeamPocahontas #LovePocahontas #PocahontasFor...,No,98
295,Merida,Merida's Adventure,2001,95,7,Yes,No,Red,Grey,Purple,...,89,309,49,3638,98,225,881,#TeamMerida #LoveMerida #MeridaForever,No,95
296,Belle,Belle's Adventure,2006,76,1,Yes,No,Red,Green,Yellow,...,97,406,53,1558,33,270,274,#TeamBelle #LoveBelle #BelleForever,No,96
297,Anna,Anna's Adventure,2020,70,2,No,Yes,White,Blue,Blue,...,72,935,25,1815,53,53,164,#TeamAnna #LoveAnna #AnnaForever,Yes,67

In [ ]:
df[df['HasAnimalSidekick']=='Yes']

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
0,Pocahontas,Pocahontas's Adventure,1977,85,4,No,Yes,Brown,Green,Pink,...,88,661,25,2524,68,298,481,#TeamPocahontas #LovePocahontas #PocahontasFor...,Yes,88
1,Mulan,Mulan's Adventure,1995,85,1,Yes,Yes,Blonde,Brown,Purple,...,91,688,52,4202,49,133,619,#TeamMulan #LoveMulan #MulanForever,Yes,78
2,Raya,Raya's Adventure,1989,110,4,No,No,Blonde,Hazel,Pink,...,76,790,54,525,68,129,230,#TeamRaya #LoveRaya #RayaForever,No,53
3,Anna,Anna's Adventure,1940,78,1,No,No,Brown,Grey,Green,...,70,820,42,1951,73,138,697,#TeamAnna #LoveAnna #AnnaForever,Yes,84
7,Rapunzel,Rapunzel's Adventure,1987,79,3,No,No,Black,Hazel,Pink,...,88,1130,58,705,73,194,988,#TeamRapunzel #LoveRapunzel #RapunzelForever,No,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,Merida,Merida's Adventure,2001,95,7,Yes,No,Red,Grey,Purple,...,89,309,49,3638,98,225,881,#TeamMerida #LoveMerida #MeridaForever,No,95
296,Belle,Belle's Adventure,2006,76,1,Yes,No,Red,Green,Yellow,...,97,406,53,1558,33,270,274,#TeamBelle #LoveBelle #BelleForever,No,96
297,Anna,Anna's Adventure,2020,70,2,No,Yes,White,Blue,Blue,...,72,935,25,1815,53,53,164,#TeamAnna #LoveAnna #AnnaForever,Yes,67
298,Tiana,Tiana's Adventure,1937,71,7,No,No,Red,Blue,Purple,...,86,463,54,2365,35,116,584,#TeamTiana #LoveTiana #TianaForever,No,76
299,Mulan,Mulan's Adventure,1938,105,3,No,No,Brown,Brown,Purple,...,77,195,42,2218,89,11,540,#TeamMulan #LoveMulan #MulanForever,No,69

In [ ]:
df['FirstMovieTitle'].unique()

array(["Pocahontas's Adventure", "Mulan's Adventure", "Raya's Adventure",
       "Anna's Adventure", "Jasmine's Adventure",
       "Snow White's Adventure", "Rapunzel's Adventure",
       "Belle's Adventure", "Cinderella's Adventure", "Ariel's Adventure",
       "Elsa's Adventure", "Aurora's Adventure", "Moana's Adventure",
       "Tiana's Adventure", "Merida's Adventure"], dtype=object)

In [ ]:
df[df['FirstMovieYear']==2010]

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
5,Jasmine,Jasmine's Adventure,2010,78,7,Yes,Yes,Brown,Blue,Blue,...,93,1245,59,555,67,216,454,#TeamJasmine #LoveJasmine #JasmineForever,Yes,61
9,Anna,Anna's Adventure,2010,108,1,Yes,Yes,Black,Brown,Pink,...,67,931,48,3995,48,113,472,#TeamAnna #LoveAnna #AnnaForever,No,96
60,Mulan,Mulan's Adventure,2010,92,6,No,No,Red,Brown,Pink,...,87,1300,42,2414,80,43,36,#TeamMulan #LoveMulan #MulanForever,No,54
118,Aurora,Aurora's Adventure,2010,84,4,Yes,No,Black,Blue,Pink,...,83,491,52,667,30,166,868,#TeamAurora #LoveAurora #AuroraForever,No,98
174,Elsa,Elsa's Adventure,2010,82,6,No,No,Black,Grey,Pink,...,61,1180,43,1197,71,54,314,#TeamElsa #LoveElsa #ElsaForever,Yes,70
212,Cinderella,Cinderella's Adventure,2010,99,3,No,No,Brown,Hazel,Purple,...,77,777,53,993,71,15,308,#TeamCinderella #LoveCinderella #CinderellaFor...,No,67
246,Elsa,Elsa's Adventure,2010,105,5,Yes,No,Red,Grey,Blue,...,94,779,60,4832,37,175,805,#TeamElsa #LoveElsa #ElsaForever,Yes,60
247,Belle,Belle's Adventure,2010,96,3,No,No,Red,Green,Pink,...,89,888,23,1720,77,31,483,#TeamBelle #LoveBelle #BelleForever,Yes,93

In [ ]:
df[df['PrincessName']>'18']

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
0,Pocahontas,Pocahontas's Adventure,1977,85,4,No,Yes,Brown,Green,Pink,...,88,661,25,2524,68,298,481,#TeamPocahontas #LovePocahontas #PocahontasFor...,Yes,88
1,Mulan,Mulan's Adventure,1995,85,1,Yes,Yes,Blonde,Brown,Purple,...,91,688,52,4202,49,133,619,#TeamMulan #LoveMulan #MulanForever,Yes,78
2,Raya,Raya's Adventure,1989,110,4,No,No,Blonde,Hazel,Pink,...,76,790,54,525,68,129,230,#TeamRaya #LoveRaya #RayaForever,No,53
3,Anna,Anna's Adventure,1940,78,1,No,No,Brown,Grey,Green,...,70,820,42,1951,73,138,697,#TeamAnna #LoveAnna #AnnaForever,Yes,84
4,Mulan,Mulan's Adventure,1943,103,7,No,Yes,White,Brown,Green,...,86,996,55,3958,34,155,200,#TeamMulan #LoveMulan #MulanForever,Yes,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,Merida,Merida's Adventure,2001,95,7,Yes,No,Red,Grey,Purple,...,89,309,49,3638,98,225,881,#TeamMerida #LoveMerida #MeridaForever,No,95
296,Belle,Belle's Adventure,2006,76,1,Yes,No,Red,Green,Yellow,...,97,406,53,1558,33,270,274,#TeamBelle #LoveBelle #BelleForever,No,96
297,Anna,Anna's Adventure,2020,70,2,No,Yes,White,Blue,Blue,...,72,935,25,1815,53,53,164,#TeamAnna #LoveAnna #AnnaForever,Yes,67
298,Tiana,Tiana's Adventure,1937,71,7,No,No,Red,Blue,Purple,...,86,463,54,2365,35,116,584,#TeamTiana #LoveTiana #TianaForever,No,76
299,Mulan,Mulan's Adventure,1938,105,3,No,No,Brown,Brown,Purple,...,77,195,42,2218,89,11,540,#TeamMulan #LoveMulan #MulanForever,No,69

In [ ]:
df[df['NumberOfSongs']>3]

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
0,Pocahontas,Pocahontas's Adventure,1977,85,4,No,Yes,Brown,Green,Pink,...,88,661,25,2524,68,298,481,#TeamPocahontas #LovePocahontas #PocahontasFor...,Yes,88
2,Raya,Raya's Adventure,1989,110,4,No,No,Blonde,Hazel,Pink,...,76,790,54,525,68,129,230,#TeamRaya #LoveRaya #RayaForever,No,53
4,Mulan,Mulan's Adventure,1943,103,7,No,Yes,White,Brown,Green,...,86,996,55,3958,34,155,200,#TeamMulan #LoveMulan #MulanForever,Yes,71
5,Jasmine,Jasmine's Adventure,2010,78,7,Yes,Yes,Brown,Blue,Blue,...,93,1245,59,555,67,216,454,#TeamJasmine #LoveJasmine #JasmineForever,Yes,61
8,Anna,Anna's Adventure,2007,94,6,Yes,No,White,Brown,Pink,...,99,1250,33,2132,34,171,506,#TeamAnna #LoveAnna #AnnaForever,Yes,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,Merida,Merida's Adventure,1953,83,6,Yes,Yes,Red,Green,Blue,...,88,409,27,1923,54,231,42,#TeamMerida #LoveMerida #MeridaForever,No,64
293,Moana,Moana's Adventure,1961,96,4,Yes,No,Black,Grey,Pink,...,78,729,50,4350,74,241,977,#TeamMoana #LoveMoana #MoanaForever,Yes,93
294,Pocahontas,Pocahontas's Adventure,2019,95,7,No,Yes,Brown,Hazel,Blue,...,68,168,23,908,94,173,847,#TeamPocahontas #LovePocahontas #PocahontasFor...,No,98
295,Merida,Merida's Adventure,2001,95,7,Yes,No,Red,Grey,Purple,...,89,309,49,3638,98,225,881,#TeamMerida #LoveMerida #MeridaForever,No,95
298,Tiana,Tiana's Adventure,1937,71,7,No,No,Red,Blue,Purple,...,86,463,54,2365,35,116,584,#TeamTiana #LoveTiana #TianaForever,No,76